### ISSUE TITLE
Sprite / Graphics editors via freeze menu

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#117]
It would be very helpful to have a sprite and graphics editor accessible from the freeze menu, to make it much easier for people to produce graphics.

**Comment by lydon42** [comment]
Sprite Editor already is a thing in mega65-freezemenu repo [mega65-freezemenu/issue#4](https://github.com/MEGA65/mega65-freezemenu/issues/4).
Just added an issue for a [Tile Editor](https://github.com/MEGA65/mega65-freezemenu/issues/26) (I think that is meant by graphics editor, because painting program is more like a separate application).
