### ISSUE TITLE
Powering on MEGA65 without SD card gives BREAK AT message

### ISSUE THREAD

**Issue by adtbm** [MEGA65/mega65-core#252]
With the latest 138-hd-5503 bitstream, when switching on MEGA65 without an SD card inserted, MEGA65 will come up with Blue screen and a BREAK AT message...
![mega65-screen-000005](https://user-images.githubusercontent.com/35996116/87261351-24e06880-c4b6-11ea-9f65-1c6d0bfe4677.png)

**Comment by gardners** [comment]
This is caused by an interrupt happening before the interrupt vectors get setup.
I'll take a look into this.

**Comment by FeralChild64** [comment]
The start does not go trough the $FFFC vector, right? Otherwise you would have SEI as the very first instruction executed. I guess there must be some garbage at $314 - if there was a $0000, the Kernal routine would have executed internal IRQ handling directly. Another possibility is the KEYLOG vector ($28F) - it is used by the IRQ keyboard scanning routine, it has to be initialized properly.

**Comment by lydon42** [comment]
Can't reproduce.
