### ISSUE TITLE
Bitplanes are not aligned with display

### ISSUE THREAD

**Issue by Edilbert** [MEGA65/mega65-core#432]
The display of bitplane graphics (BASIC 65) is shifted by 1 scanline downwards.
It appears in all resolution and can be tested for example in 320 x 200 resolution:

100 SCREEN 320,200,1
110 LINE 0,0,319,0
120 LINE 0,199,319,199
130 GETKEY A$
140 SCREEN CLOSE

For example LINE 0,0,319,0 is displayed on scanline 1 instead of 0.
LINE 0,199,319,199 isn't displayed at all.

**Comment by frehwagen** [comment]
The issue is related to the rendering integration of the bitplanes (as part of the sprite pipeline) and the viciv video signal composition. Especially the vic lines and physical video signal lines integration received and rework that causes the problem with the bitplanes.

There are 2 ways to fix the issues:
1.) start/stop rendering the bitplanes 1 physical output line later
2.) fetch the data one interlace line earlier

I followed the 2nd because, even if the solution seems a bit off, it keeps the rendering area as it is implemented now and the overall effort lower because the internal bitplan logic so far was not aware on interlaced line position at all.
