### ISSUE TITLE
Where is the source code of the MAX10 FPGA POF File and what is use for?

### ISSUE THREAD

**Issue by benitoss** [MEGA65/mega65-core#456]
In the mega65-book.pdf documentation, page 1060, is shown the scheme of MAX10 and there are lines relative to keyboard and Joysticks connected to MAX10 FPGA plus 2 lines (RX and TX) connected to Artix7 200 FPGA. However, in the documentation is not explained, unless the programming of the FPGA with Quartus, the use of the MAX10 FPGA. Please, could you clarify this issue?
Likewise, I would like to know if is available the source code of the POF file that is used in Quartus to program the MAX10 FPGA.

Thanks and regards

**Comment by rdpeake** [comment]
Max 10 source is here: https://twitter.com/Twitch/status/1445770441176469512?t=Fik5jFM0v3RSjZDeGa6_GQ&s=19

At present it is mostly used for reset button and the expansion port on the main board. It was added at recommendation of teens in order to be able to unbrick the 200t as the JTAG lines for the max10 are connected to the external as card. There are also people investigating the possibility of using the max 10 to boot from as card images

**Comment by rdpeake** [comment]
Note, don't make a comment from mobile, it will be full or typos...
