### ISSUE TITLE
High-quality high-speed random number generator (neoTRNG)

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#600]
**Is your feature request related to a problem? Please describe.**
The MEGA65 currently lacks a high-speed good-quality hardware random number generator.  Having one would make a lot of software easier to write, for example to simulate the behaviour of various productivity software.

**Describe the solution you'd like**
A free IO register should return a fresh random value whenever read.

**Describe alternatives you've considered**
Doing nothing. Always a noble option.

**Additional context**
None

**Comment by gardners** [comment]
Use neoTRNG

**Comment by lydon42** [comment]
Problem is the toggle of trng_consume_toggle happening in function read_data_complex: you can not change signals within functions.
Workaround using write to RNG register for toggelung results in random bytes read.
Trying different method of toggling on read outside of the function next.

**Comment by lydon42** [comment]
# Testing the RNG
It seems that the RNG takes a lot of cycles to produce a new number. The picture shows the number changing every 16-22 bytes. The loop takes 16 cycles, which translates to 256 to 352 cycles for a new number.
This means to me that we need access to the valid bit of neoTRNG so that software can determine if the RNG already has a new number.
![mega65-screen-000000](https://github.com/MEGA65/mega65-core/assets/16632479/cfae8e54-0c5b-4923-99b2-5ef057e30cbc)
