### ISSUE TITLE
80x50 text mode missing bottommost pixel row in NTSC only

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-core#671]
**Test Environment (required)**
 - Platform: MEGA65
 - Core Commit: 93d55f0
 - ROM Release: 920382/990003

**Describe the bug**
The VIC-IV 80x50 text display mode does not display the bottommost pixel row in NTSC. It displays all pixel rows in PAL.

I noticed this in the 80x50 text mode as implemented by ROM 920382/990003, which adds an operating mode in this resolution to the BASIC editor. I assume this is *not* specific to that implementation but general to this VIC-IV display mode.

**To Reproduce**
1. Install ROM 990003.
2. Ensure the MEGA65 is in NTSC video mode.
3. Press ESC then 5 to enter 80x50 text mode.
4. Cursor to the bottommost text row. Type characters with set pixels in the bottommost row, e.g. `j`, `y`, `;`, `,`, or many PETSCII graphics characters. Notice the bottommost pixel row is missing.
5. Switch to PAL mode. Notice the bottommost pixel row is present.

**Expected behavior**
All pixel rows should display in both NTSC and PAL.

**Screenshots**
![IMG_1291 Medium](https://user-images.githubusercontent.com/408973/220819419-5d78bb93-bdde-42a7-97ce-111404eb3faa.jpeg)

**Comment by ki-bo** [comment]
Looking at the code, I can confirm that NTSC is currently only displaying 399 raster lines between top and bottom border by default. But the root cause is actually that the top border is ending one line earlier than expected. Since the position of the character generator initializes according to the top border position, the last line is actually missing. A correct fix is moving the top border up by one pixel while letting the bottom border as is.
