### ISSUE TITLE
Long delay before booting to open rom when no SD cards inserted.

### ISSUE THREAD

**Issue by cybern0id** [MEGA65/mega65-core#713]
**Test Environment (required)**
 - Platform: MEGA65
 - Core Commit: 683-cartflash,20230619.10,be40797
 - ROM Release: 920377+

**Describe the bug**
Since release of development core build [#6](https://builder.mega65.org/job/mega65-core/job/development/6/), when booting with no SD cards inserted, there is a not insignificant delay of approximately 60 seconds before the open rom is loaded. The status splash screen displays "Trying SDCARD BUS 0" as last message during the delay. Previous behaviour (in release 0.95 core) was to boot immediately to open rom. Likely a side-effect of the fix for issue https://github.com/MEGA65/mega65-core/issues/669

<img width="802" alt="Screenshot 2023-06-21 at 17 30 33" src="https://github.com/MEGA65/mega65-core/assets/983274/bb008a5d-cf7f-48ae-9d63-66f665685adb">

**To Reproduce**
1. Remove all SD cards
2. Boot any development or 683-cart core since develop build 6

**Expected behavior**
No boot delay and immediate loading of open rom.

**Comment by gurcei** [comment]
I had a fix underway for this, on the `fix_long_delay_to_openrom` branch. Think I made progress with this, but will try revisit it soon to recall where I was at with it.

**Comment by gurcei** [comment]
Ok, have tested it on my m65 hardware:
- With all sdcards removed, it now jumps straight to open rom.

In addition, I tweaked hyppo so that if there is an sd-card found, but no MEGA65.ROM image exists on it, it will boot to open-rom.

Prior behaviour was that this condition would cause the system to reset, which wasn't very useful. At least if an empty sd-card could boot to openrom, you're still in a good position to use mega65_ftp tool to populate the sd-card with any missing files like MEGA65.ROM.

Will make a PR for this.

**Comment by gurcei** [comment]
Ok, I've merged this into development branch, should be sorted now.
